### PR TITLE
Version bump to 1.3.2

### PR DESCRIPTION
**Pull request by rth**
Updating PyKrige to the latest version ~~1.3.1~~ 1.3.2 on PyPi.

### CODE REVIEW

**Comment by rth** [comment]
> Using pinned numpy packages is a deprecated pattern. Consider using the method outlined here.

The `meta.yml` has,
```yml
  build:
    - numpy x.x
  run:
    - numpy x.x
```
so it's not pinned. I read the docs but I don't see what is wrong with this. Am I missing something or is deprecation message not accurate?

**Comment by ocefpaf** [comment]
> so it's not pinned.

`numpy x.x` translate to a matrix pinned to all available `numpy` (currently conda-forge will build 1.11, 1.12 and 1.13).

> I read the docs but I don't see what is wrong with this.

It is not "wrong," just deprecated b/c it is limiting to those `numpy` version above and waste CI resources by build the package multiple times. (BTW always send PR from a fork, here you doubled that wasted by triggering the CIs twice b/c you sent the PR from the same origin.)

> Am I missing something or is deprecation message not accurate?

I don't think you missed anything and the message could probably be better. (But we don't want big linter messages :wink:). If you have any suggestions for the docs please let us know.

PS: I do recommend changed to the new way of building against `numpy`. The advantages are:

- one can go to older versions than 1.11 if you need;
- no need to rebuild to every time a new `numpy` is released;
- the 3-item build matrix will be reduced to 1 and save us tons of CI time.

**Comment by rth** [comment]
> numpy x.x translate to a matrix pinned to all available numpy (currently conda-forge will build 1.11, 1.12 and 1.13).

Thanks for the explanations! Got it: will switch to the new notation in the next update..

> always send PR from a fork, here you doubled that wasted by triggering the CIs twice b/c you sent the PR from the same origin

Aww, I was wondering why there were two identical buids per CI provider. Makes sense now.

> If you have any suggestions for the docs please let us know.

Well, maybe just mention what `numpy x.x` does in [the docs](https://conda-forge.org/docs/meta.html#building-against-numpy) and say it's deprecated, then mention the new way of linking against numpy in the [staged-recepes README](https://github.com/conda-forge/staged-recipes#4-what-does-numpy-xx-mean) ? I can make a PR..

**Comment by ocefpaf** [comment]
> Well, maybe just mention what `numpy x.x` does in [the docs](https://conda-forge.org/docs/meta.html#building-against-numpy) and say it's deprecated,

Yep. That would be very useful.

> then mention the new way of linking against numpy in the [staged-recepes README](https://github.com/conda-forge/staged-recipes#4-what-does-numpy-xx-mean) ?

I am not too keen to clutter staged-recipes README with docs. The linter will catch that and point people to the docs. Anyways, I would not oppose if people think that is better.

>  I can make a PR.

Thanks! Ping me for a review/merge if you do.

**Comment by rth** [comment]
> I am not too keen to clutter staged-recipes README with docs. The linter will catch that and point people to the docs. Anyways, I would not oppose if people think that is better.

I agree, but my point is that the staged-recepes README currently kind of suggest using `numpy x.x` for linking numpy,  so IMO that section should be either removed or clearly marked as deprecated...

**Comment by ocefpaf** [comment]
> I agree, but my point is that the staged-recepes README currently kind of suggest using `numpy x.x` for linking numpy,  so IMO that section should be either removed or clearly marked as deprecated...

Oh yes! I totally missed that!! It must be removed.

**Pull request merged**
